### ISSUE TITLE
<no message> on Exceptions when using new sentry/sentry package

### ISSUE THREAD

**Issue by bendubuisson** [camspiers/silverstripe-loggerbridge#10]
Hey @camspiers , when using the newer package `sentry/sentry` over the older `raven/raven` package, it does not log a message for general Exceptions. Any ideas? (the rest is fine but we get a `<no message value>` message on Sentry :(

Tested on another website with `raven/raven` and that's working fine.

**Comment by camspiers** [comment]
I'd guess the API changed in some way. Fire up xdebug and put a breakpoint during a relevant part of the flow, you should be able to track it down.

**Comment by bendubuisson** [comment]
I feel like updates of the `RavenHandler` class in newer versions of Monolog might fix that. Having a try...

**Comment by bendubuisson** [comment]
OR we need to update our version of Sentry 😄 https://github.com/Seldaek/monolog/issues/867

**Comment by bendubuisson** [comment]
looks like the exception message is  being passed from Monolog to Sentry as `$options['extra']['message'] ` where Sentry expects `$options['message'] `
Not sure whether to take it to Monolog or Sentry?

**Comment by bendubuisson** [comment]
Have done a PR to monolog https://github.com/Seldaek/monolog/pull/1017
